# Generated by Django 3.1 on 2020-09-01 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
