# Generated by Django 3.1 on 2020-08-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('prize', models.CharField(blank=True, max_length=100)),
                ('tournament_format', models.CharField(max_length=100)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=4)),
                ('directions', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
