# Generated by Django 3.1 on 2020-08-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='ending_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
