# Generated by Django 3.1 on 2020-08-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20200831_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
