# Generated by Django 3.1 on 2020-09-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20200831_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
